---
sudo: true
language: ruby
cache: bundler
bundler_args: --without system_tests
matrix:
  include:
   - rvm: 2.4.1
     env: PUPPET_GEM_VERSION='~> 5.0.0' STRICT_VARIABLES=yes COVERAGE=yes
script:
  - bundle exec rake spec
  - sudo apt-get update
  - sudo apt-get install puppetserver
  - sudo puppet module install garethr-docker
  - sudo puppet module install rtyler/jenkins
  - puppet cert clean ciscopm1.tidalsoft.local
  - puppet cert generate ciscopm1.tidalsoft.local
  - sudo puppet agent --enable
  - sudo puppet agent --test
  - cat /etc/passwd
  - sudo netstat -tunpl
branches:
  only:
  - master
