---
sudo: true
language: ruby
cache: bundler
bundler_args: --without system_tests
matrix:
  include:
   - rvm: 2.4.1
     env: PUPPET_GEM_VERSION='~> 5.0.0' STRICT_VARIABLES=yes COVERAGE=yes
script:
  - bundle exec rake spec
  - wget https://apt.puppetlabs.com/puppet-release-jessie.deb
  - sudo dpkg -i puppet-release-jessie.deb
  - sudo apt-get update
  - sudo apt-get install puppetserver
  - sudo service puppetserver start
  - sudo puppet module install garethr/docker
  - sudo puppet module install rtyler/jenkins
  - sudo puppet agent --enable
  - sudo puppet agent --test
  - cat /etc/passwd
  - sudo netstat -tunpl
branches:
  only:
  - master
