---
sudo: true
language: ruby
cache: bundler
bundler_args: --without system_tests
matrix:
  include:
   - rvm: 2.4.1
     env: PUPPET_GEM_VERSION='~> 5.0.0' STRICT_VARIABLES=yes COVERAGE=yes
script:
  - bundle exec rake spec
  - cat /etc/*-release
  - uname -a
  - sudo apt-get update
  - sudo apt-get install puppetmaster-passenger
  - sudo puppet module install garethr-docker
branches:
  only:
  - master
