---
sudo: true
language: java
jdk: oraclejdk8

script:
  - export TZ="America/New_York"
  - date
  - pwd
  - export ROOT_DIR="`pwd`"
  - find . -ls
  - cat /etc/*-release
  - hostname
  - hostname -d
  - java -version
  - which java
  - who am i
  - whoami
  - sudo who am i
  
  # Install ruby
  #- curl -sSL https://get.rvm.io | sudo bash -s stable --ruby
  #- sudo /home/travis/.rvm/bin/rvm install ruby --latest
  #- sudo apt-get install ruby-full
  #- sudo gem install puppetlabs_spec_helper
  #- sudo gem install facter
  #- bundle install
  #- sudo gem install puppet
  
  # Install puppet server
  #- sudo apt-get update
  #- bundle exec rake spec
  - cd /tmp
  - pwd
  - wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
  - sudo dpkg --force-all -i puppetlabs-release-trusty.deb
  - cd ~
  - sudo apt-get update
  - sudo apt-get install puppetserver
  - sudo apt-get update
  #- sudo puppet plugin download
  - sudo puppet resource package puppetserver ensure=latest
  - sudo puppet resource service puppetserver ensure=running enable=true
  
  # Install puppet agent
  - sudo apt-get install puppet
  - sudo sed -i 's/START=no/START=yes/g' /etc/default/puppet
  - sudo apt-get update
  - sudo puppet resource package puppet ensure=latest
  - sudo puppet resource service puppet ensure=running enable=true
  - puppet --version
  - puppet master --version 
  - puppet agent --version
  - puppet config print
  - ps -ef
  
  # Set hostname
  - ls -l $ROOT_DIR/bin/deploy_root
  - sudo sh -c $ROOT_DIR/bin/deploy_root $ROOT_DIR
  - sudo sh -c $ROOT_DIR/bin/deploy_puppet $ROOT_DIR
  - sudo hostname puppetmaster.localdomain
  - sudo hostname puppet.localdomain
  - find ~/.puppet -ls
  
  # Sign certs
  - sudo puppet cert generate puppetmaster.localdomain
  - puppet apply --configprint manifest
  - sudo puppet apply --parser=future $(puppet apply --configprint manifest)
  - sudo puppet cert list --all
  #- sudo puppet cert sign --all
  - sudo puppet config set server puppet.localdomain --section agent
  
  # Start pupper server
  #- sudo service puppetmaster start
  - sudo ps -ef | egrep puppet
  
  # Start pupper agent
  #- sudo service puppet start
  - puppetserver gem list           
  
  # Install puppet modules
  - sudo puppet module install rtyler/jenkins
  
  # Run modules
  - sudo puppet agent -t
  - ls -l /etc/puppet/modules
  #- sudo puppet apply site.pp
  - sudo puppet apply --parser=future ~/puppet_dir/modules/jenkins/manifests/init.pp
  - sudo puppet apply --parser=future -e "include jenkins"
  
  # Test agent
  - cd /tmp && wget http://mirrors.jenkins.io/war-stable/latest/jenkins.war
  - sudo /bin/su - jenkins -c "$JAVA_HOME/bin/java -jar /tmp/jenkins.war --httpPort=8080" &
  - sleep 5
  - sudo ps -ef | egrep jenkins
  - sudo ps -ef | egrep docker
  - cat /etc/passwd
  - sudo netstat -tunpl
  - cat /home/travis/.puppetlabs/var/log/puppetd.log
  - env | sort
  - echo Done
  
branches:
  only:
  - master
