---
sudo: true
language: ruby
cache: bundler
bundler_args: --without system_tests
matrix:
  include:
   - rvm: 2.4.1
     env: PUPPET_GEM_VERSION='~> 5.0.0' STRICT_VARIABLES=yes COVERAGE=yes
script:
  - bundle exec rake spec
  - cat /etc/*-release
  - wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
  - sudo dpkg -i puppetlabs-release-trusty.deb
  - sudo apt-get update
  - sudo apt-get install puppetserver
  - which puppet
  - sudo which puppet
  - sudo puppet module install garethr/docker
  - sudo puppet module install rtyler/jenkins
  - sudo puppet agent --enable
  - sudo puppet cert generate ciscopm1.tidalsoft.local
  - sudo /usr/sbin/service pe-httpd restart
  - sudo iptables -L
  - sudo puppet agent --test
  - cat /etc/passwd
  - sudo netstat -tunpl
branches:
  only:
  - master
