---
sudo: true
language: ruby

addons:
  apt:
    packages:
      - xvfb
      - figlet
      - toilet

install:
  - export DISPLAY=':99'
  - export TZ='America/New_York'
  - sudo apt-get install openjdk-7-jre-headless
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sudo apt-get update
  - wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
  - sudo dpkg --force-all -i puppetlabs-release-trusty.deb
  - sudo apt-get -y install ntp 
  - sudo apt-get update
  - sudo apt-get install puppetmaster
  - sudo apt-get update
  - sudo apt-get install puppet
  - sudo puppet resource package puppetmaster ensure=latest
  - sudo puppet resource service puppetmaster ensure=running enable=true
  - sudo puppet agent
  
script:
  - toilet -f mono12 `date '+%y-%m-%d%n%H.%M'`
  - export JENKINS_HOME=/var/lib/jenkins
  - sleep 5
  - sudo sh -c bin/deploy_puppet
  
  - export CDIR="$(sudo puppet config print confdir)"
  - sudo puppet apply $CDIR/manifests/site.pp
  - sudo ls -l /etc/init.d
  
  - sleep 5
  - export CLI="$( sudo find / -name jenkins-cli.jar -print 2>/dev/null | sed -n 1p )"
  - export PASS="$( sudo cat /var/lib/jenkins/secrets/initialAdminPassword )"
  - export CRUMB=$(curl -s 'http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)' -u admin:$PASS)
  - xargs sudo java -jar $CLI -auth "admin:$PASS" -s http://127.0.0.1:8080 install-plugin < jenkins_dir/plugins.list
  - export CRUMB=$(curl -s 'http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)' -u admin:$PASS)
  #- curl --user admin:$PASS -d "$CRUMB" --data-urlencode "script=$(<./jenkins_dir/dsl/pipeline.groovy)" http://127.0.0.1:8080/scriptText
  #- curl -s -XPOST 'http://127.0.0.1:8080/createItem?name=Pipeline' -u admin:$PASS --data-binary @./jenkins_dir/jobs/config.xml -H "$CRUMB" -H "Content-Type:application/xml"
  - sudo mkdir -p /var/lib/jenkins/jobs/Pipeline
  - sudo cp ./jenkins_dir/jobs/config.xml /var/lib/jenkins/jobs/Pipeline
  - sudo chown jenkins /var/lib/jenkins/jobs/Pipeline
  - sudo chown jenkins /var/lib/jenkins/jobs/Pipeline/config.xml
  - sudo /etc/init.d/jenkins force-reload
  - sudo /etc/init.d/jenkins restart
  - sleep 5
  - echo "CRUMB=$CRUMB"
  - sudo ps -ef | egrep jenkins
  - sudo netstat -tunpl
  - sudo java -jar "$CLI" -auth "admin:$PASS" -remoting -s http://127.0.0.1:8080 build 'Pipeline' 
  - echo Done
