---
sudo: true
language: java
jdk: oraclejdk8
  
branches:
  only:
  - master

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  
script:
  - export TZ="America/New_York"
  - export ROOT_DIR="`pwd`"
  - export DISPLAY=:99
  - date
  - cat /etc/*-release 
  
  # Install puppet server
  - wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
  - sudo dpkg --force-all -i puppetlabs-release-trusty.deb
  - sudo apt-get update
  - sudo apt-get install puppetserver
  - sudo apt-get update
  - sudo puppet resource package puppetserver ensure=latest
  - sudo puppet resource service puppetserver ensure=running enable=true
  
  # Install puppet agent
  - sudo apt-get install puppet
  - sudo sed -i 's/START=no/START=yes/g' /etc/default/puppet
  - sudo apt-get update
  - sudo puppet resource package puppet ensure=latest
  - sudo puppet resource service puppet ensure=running enable=true
  - puppet --version
  - puppet master --version 
  - puppet agent --version
  - ps -ef
  
  # Set hostname
  - sudo sh -c $ROOT_DIR/bin/deploy_root $ROOT_DIR
  - sudo sh -c $ROOT_DIR/bin/deploy_puppet $ROOT_DIR
  - sudo hostname puppetmaster.localdomain
  - sudo hostname puppet.localdomain
  
  # Sign certs
  - sudo puppet cert generate puppetmaster.localdomain
  - puppet apply --configprint manifest
  - sudo puppet apply $(puppet apply --configprint manifest)
  - sudo puppet cert list --all
  - sudo puppet config set server puppet.localdomain --section agent
  - sudo puppet agent --no-daemonize --server puppet.localdomain --onetime --verbose
  - sudo puppet cert --list
  - sudo puppet cert sign --all
  
  # Install puppet modules
  - sudo puppet module install rtyler/jenkins
  
  # Run modules
  - sudo rm -f /var/lib/puppet/ssl/certificate_requests/puppet.localdomain.pem
  - sudo puppet agent -t
  - sudo puppet apply /etc/puppet/modules/jenkins/manifests/init.pp
  - sudo puppet apply -e "include jenkins"
  
  # Test agent
  - sudo ps -ef | egrep jenkins
  - sudo ps -ef | egrep docker
  - cat /etc/passwd
  - sudo netstat -tunpl
  - cat /home/travis/.puppet/var/log/puppetd.log
  - env | sort
  - echo Done
