---
sudo: true
language: go

addons:
  apt:
    packages:
      - xvfb
      - figlet
      - toilet

install:
  - export DISPLAY=':99'
  - sudo apt-get install openjdk-7-jre-headless
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sudo apt-get update
  - wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
  - sudo dpkg --force-all -i puppetlabs-release-trusty.deb
  - sudo apt-get update
  - sudo apt-get install puppetserver
  - sudo apt-get update
  - sudo puppet resource package puppetserver ensure=latest
  - sudo puppet resource service puppetserver ensure=running enable=true
  
script:
  - export TZ='America/New_York'
  - export ROOT_DIR=`pwd`
  - toilet -f mono12 `date '+%y-%m-%d%n%H.%M'`
  - cat /etc/*-release 
  - ps -ef | egrep puppet
  - ps -ef | egrep docker
  - cat /etc/passwd
  - sudo netstat -tunpl
  - env | sort
  - sudo find / -name manifests -type d 2>/dev/null
  - sudo puppet config print modulepath 
  - sudo find / -name puppet.conf
  - sudo cat /etc/puppet/puppet.conf
  
  - sudo sh -c $ROOT_DIR/bin/deploy_puppet
  
  - sudo puppet apply /home/travis/.puppet/modules/foo/manifests/init.pp
  
  - sudo find /etc/puppet -ls
  - sudo cat /etc/puppet/puppet.conf
  - puppet master --configprint manifest
  - ls -l /tmp/hello
  - cat /tmp/hello
  
  - echo Done
