sudo: true
language: shell
script:
- curl https://raw.githubusercontent.com/tjordanchat/jenkins_setup/master/installer2.sh
  | bash
- echo Done
before_deploy:
- git config --local user.name "tjordanchat"
- git config --local user.email "tjordanchat@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: "KtH/x0PWrNdhFFnb6CXFuPqj0TQgUpqV9zs7Wcy4EXb4q2d1hO6GkpwqiWX0tC9ELv4dysSVcTM7rrXHolx6N7DgZh5ut6bz2jfyUvPn0SfMD2nuhXU3Xg3PqHGdGswXeFY9O/AzAPeEpYGbQgU/9jal8TRC1nuuRBhhTQAyn+i7/xVdY9uBXJ0HwM6Io9rpU1M4qmzp6kGRxO2hNPyejazEZCEjmQe6/y3ketc7WlXqL+P26K58MRHntI3w7BSHTyL5ZUMnDmPTzYW/Y6/4WBUjFZ8e0H2alUhnawFbgXIX5pySkWPEBNmEusoXkjKJBu3BX7r74GAxjg67A2zitgmRcctS/F7F2PvT+WTOeuEA05Gt/vHdc3BehuibLYI3Kgd3hLFeB0T/ilBvK+3H6bZvJ84TywKd2MFZZ0Q3+8NFKUG6FGnhIqNdqZTtY1vH+boEucdMsUzzT1Cex5mXC8KK3WTW5a9sb/H00cVEsCLGk6xMt5J5lSPWdKTl5mpUT6ze59bGrnmbX6fuXWo2GZJ3z0D/IkqLzmdftR7UBUECX59kzWyNCI74AwBC+PQmHSlQAd8l5YvefwjlS99SYw/LslhA6F0EADJt+H+zvuvsScLWrkab/mXokOOxsihFsgrpVidTVDxR3D2+d/ACwo3K/AVu6G9yS3PLioa23nc="
  file: thumbnail.png
  skip_cleanup: true
  overwrite: true
  on:
    repo: tjordanchat/jenkins_setup
