---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
matrix:
  include:
   - rvm: 2.4.1
     env: PUPPET_GEM_VERSION='~> 5.0.0' STRICT_VARIABLES=yes COVERAGE=yes
before_script:
  - bundle exec rake check_line_endings
  - bundle exec rake validate_ruby_syntax
  - bundle exec rake syntax
  - bundle exec rake lint
  - bundle exec rake metadata_lint
  - bundle exec rake validate_yaml
script:
  - bundle exec rake spec
branches:
  only:
  - master
