---
sudo: true
language: ruby
cache: bundler
bundler_args: --without system_tests

matrix:
  include:
   - rvm: 2.4.1
     env: PUPPET_GEM_VERSION='~> 5.0.0' STRICT_VARIABLES=yes COVERAGE=yes

script:
  - date
  - cat /etc/*-release
  - hostname
  - hostname -d
  
  # Set hostname
  - sudo cp hosts /etc/hosts
  - sudo cp head /etc/resolvconf/resolv.conf.d/head
  - sudo hostname puppetmaster.localdomain
  - sudo hostname puppet.localdomain
  
  # Install puppet server
  - sudo apt-get update
  - bundle exec rake spec
  - sudo mkdir -p /home/travis/.puppet/manifests/
  - wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
  - sudo dpkg --force-all -i puppetlabs-release-trusty.deb
  - sudo apt-get install puppetserver
  - sudo apt-get update
  
  # Install puppet agent
  - sudo apt-get install puppet
  - sudo sed -i 's/START=no/START=yes/g' /etc/default/puppet
  - sudo apt-get update
  - sudo puppet resource package puppetmaster ensure=latest
  - puppet -V
  
  
  # Deploy files
  - sudo cp site.pp /home/travis/.puppet/manifests/site.pp
  - sudo cp -f puppet.conf /etc/puppet/puppet.conf
  
  # Sign certs
  - sudo puppet cert generate ciscopm1.tidalsoft.local
  - sudo puppet resource package puppet ensure=latest
  - sudo puppet resource service puppet ensure=running enable=true
  - sudo puppet apply $(puppet apply --configprint manifest)
  - sudo puppet cert list --all
  - sudo puppet cert sign --all
  - sudo puppet config set server puppet.localdomain --section agent
  
  # Start pupper server
  - sudo service puppetmaster start
  - sleep 5
  - sudo ps -ef | egrep puppet
  
  # Start pupper agent
  - sudo service puppet start
  
  # Install puppet modules
  - sudo puppet module install garethr/docker
  - sudo puppet module install rtyler/jenkins
  
  
  # Test agent
  - sudo puppet agent -t --noop
  
  - echo Done
  
branches:
  only:
  - master
