---
sudo: true
language: ruby
cache: bundler
bundler_args: --without system_tests
matrix:
  include:
   - rvm: 2.4.1
     env: PUPPET_GEM_VERSION='~> 5.0.0' STRICT_VARIABLES=yes COVERAGE=yes
script:
  - bundle exec rake spec
  - sudo apt-get update
  - sudo apt-get install puppetmaster-passenger
  - sudo puppet module install garethr-docker
  - echo | sudo tee -a /etc/hosts
  - echo 127.0.0.1 localhost puppet | sudo tee -a /etc/hosts
  - sudo puppet module install rtyler/jenkins
  - sudo puppet agent --enable
  - sudo puppet --server localhost agent --test
  - cat /etc/passwd
  - sudo netstat -tunpl
branches:
  only:
  - master
