---
sudo: true
language: ruby

addons:
  apt:
    packages:
      - xvfb
      - figlet
      - toilet

install:
  - export DISPLAY=':99'
  - export TZ='America/New_York'
  - sudo apt-get install openjdk-7-jre-headless
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sudo apt-get update
  - wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
  - sudo dpkg --force-all -i puppetlabs-release-trusty.deb
  - sudo apt-get -y install ntp 
  - sudo apt-get update
  - sudo apt-get install puppetmaster
  - sudo apt-get update
  - sudo apt-get install puppet
  - sudo puppet resource package puppetmaster ensure=latest
  - sudo puppet resource service puppetmaster ensure=running enable=true
  - sudo puppet agent
  
script:
  - toilet -f mono12 `date '+%y-%m-%d%n%H.%M'`
  - export JENKINS_HOME=/var/lib/jenkins
  - sleep 5
  - sudo sh -c bin/deploy_puppet
  
  - export CDIR="$(sudo puppet config print confdir)"
  - sudo puppet apply $CDIR/manifests/site.pp
  
  - sleep 5
  - set -x
  - export CLI="$( sudo find / -name jenkins-cli.jar -print 2>/dev/null | sed -n 1p )"
  - export PASS="$( sudo cat /var/lib/jenkins/secrets/initialAdminPassword )"
  - export CRUMB=$(curl -s 'http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)' -u admin:$PASS)
  - xargs sudo java -jar $CLI -auth admin:$PASS -s http://127.0.0.1:8080 install-plugin < jenkins_dir/plugins.list
  #- sudo git clone https://github.com/cfpb/jenkins-as-code-starter-project.git
  #- cd ./jenkins-as-code-starter-project; ./gradlew rest -Dusername=admin -Dpassword=$PASS -DbaseUrl=http://localhost:8080 -Dpattern=../jenkins_dir/dsl/pipeline.   groovy; cd -
  #- bin/create_job $PASS
  - sudo ps -ef
  - sudo netstat -tunlp
  #- sudo curl -v -s -X POST 'http://127.0.0.1:8080/createItem?name=Pipeline' -u admin:$PASS --data-binary @jenkins_dir/jobs/config.xml -H "$CRUMB" -H "Content-Type:text/xml"
  - nl -b < /home/travis/.travis/job_stages
  - sudo java -jar $CLI -auth admin:$PASS -s http://127.0.0.1:8080 create-job Pipeline < jenkins_dir/jobs/config.xml
  - sudo java -jar $CLI -auth admin:$PASS -s http://127.0.0.1:8080 build 'Pipeline' 
  - echo Done
